services:
  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: url-shortener-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d


volumes:
  db_data:
